version: '3.8'
services:
  fastapi_app:
    build: .
    restart: always
    environment:
      - ENV=production
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
    networks:
      - loopbill_network
  nginx:
    image: nginx:alpine
    depends_on:
      - fastapi_app
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - loopbill_network
networks:
  loopbill_network:
    driver: bridge